### ISSUE TITLE
Scale and Sign of the real and imaginary parts

### ISSUE THREAD

**Issue by echo66** [dntj/jsfft#3]
Greetings!

I'm comparing the output of fft.js with MATLAB fft implementation and there are two issues worth nothing:
- The imaginary part sign, in fft.js, is always different from the "golden standard" (MATLAB).
- The scale of both imaginary and real parts, in fft.js, appears to be already scaled by (1/sampleRate).

Take a look at this example: http://pastiebin.com/54c3d0ae2e413

**Comment by dntj** [comment]
Hey, thanks for the note.  Both the issues you note are entirely conventional, but they point out that the documentation here is a little lacking.   I'll update the README to note the conventions used.

You can easily map the result into MATLAB's convention with the mapper on the ComplexArray of the transformed data should you need to.

**Comment by soanvig** [comment]
Hi, **dntj**. I will stick up to this topic!

I've got the question about scaling. I'm creating 8192 samples of cosinus function (amplitude = 1, frequency = 3Hz). The signal generates as it should.

Now I do `.fft()`, and `.magnitude()`, print the results to the plot, and there are two spikes: 3Hz and -3Hz (like it should), but the amplitude is 45. I know I should do scaling, but I have no idea what parameters should I use, because the 45 (compared to 1) is no-meaning number.

**Comment by dntj** [comment]
@soanvig, your amplitude of 45 comes from the fact that a cosine with have two frequency components of magnitude `N/2/√N` which is `~45` for with `N = 8192`.

I've added a note about conventions to the readme to this effect.

**Comment by soanvig** [comment]
I'm not the best with that topic. Is it enough that I scale **any** signal (i.e. sum of sin and cos) by this `N/2/sqrt(N)` factor?

**Comment by dntj** [comment]
If you'd like to scale individual frequencies down to have amplitude 1 in the transformed signal, then multiplying by `1/(N/2/sqrt(N))` should do it.

**Comment by soanvig** [comment]
Thank you. I will play with it. I'm using your library in my engineering project.
